# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186f0dbb251f5c90907c65f83d30b81854d3ca4bfeaaa69cb57bf1d26f8b182ccbbef6fede6a3cffbff719a16faa58597378cf2723a42b8968e9378241a91015

test:
  secret_key_base: 1d5d0ada680b8af7b387b04498dbbc3fec35979728230986c676d2aeb26f26f99144177e533218f85dfdd1c7614782d56a5c9ff54cd65101fa169c21b963a18e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 186f0dbb251f5c90907c65f83d30b81854d3ca4bfeaaa69cb57bf1d26f8b182ccbbef6fede6a3cffbff719a16faa58597378cf2723a42b8968e9378241a91015
